#!/usr/bin/env bash
#Petit script pour régler facilement le bon fuseau horaire dans le web terminal de Holy Claude
#zf260518.1831

# source: 

echo -e "
ATTENTION: IL FAUT FAIRE TOURNER CE SCRIPT DIRECTEMENT DANS LE WEB TERMINAL !


"

date
echo "export TZ=Europe/Zurich" >> ~/.bashrc && source ~/.bashrc
date

